name: my_budget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  cloud_firestore: ^6.0.1
  rxdart: ^0.28.0
  intl: ^0.20.2
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
