// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8h5Enfe9YiXWC8jEdClXwKOeUypnd44',
    appId: '1:405355258715:web:90e7071298bf8426ac307e',
    messagingSenderId: '405355258715',
    projectId: 'my-budget-b5048',
    authDomain: 'my-budget-b5048.firebaseapp.com',
    storageBucket: 'my-budget-b5048.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZBGMZBvWfYH08nZjDHCcsFBvQWsP-dM',
    appId: '1:405355258715:android:ed7fc34d7f87f123ac307e',
    messagingSenderId: '405355258715',
    projectId: 'my-budget-b5048',
    storageBucket: 'my-budget-b5048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcz8ImD2glDASyIeZJBNSSbiqU8ZpA15c',
    appId: '1:405355258715:ios:fddbe3d0a90e6e97ac307e',
    messagingSenderId: '405355258715',
    projectId: 'my-budget-b5048',
    storageBucket: 'my-budget-b5048.firebasestorage.app',
    iosBundleId: 'com.example.myBudget',
  );
}
